const Config = {
  schema: {
    client_secret: {
      title: 'Client Secret',
      type: 'string',
      default: '',
      description: 'The contents of the `client_secret.json` file downloaded from the Google Developers Console. See the Installation section of the README for instructions.',
      order: 1
    },
    oauth_token: {
      title: 'OAuth2 Token',
      type: 'string',
      default: '',
      description: 'OAuth2 token generated by atom-gmail:authenticate. Do not touch this manually.',
      order: 2
    },
    code_highlighting: {
      title: 'Code highlighting style',
      type: 'string',
      enum: css_options,
      default: 'github',
      description: 'See [https://highlightjs.org/static/demo/](https://highlightjs.org/static/demo/) to inspect styles.',
      order: 3
    },
    max_width: {
      title: 'Maximum width',
      type: 'string',
      default: '720px',
      description: 'Maximum width of email. Can be pixels or percent. See [here](https://www.w3schools.com/cssref/pr_dim_max-width.asp) for reference.',
      order: 4
    },
    centered: {
      title: 'Centered',
      type: 'boolean',
      default: true,
      description: 'Center text in email',
      order: 5
    },
    linkify: {
      title: 'Linkify',
      description: 'Autoconvert URL-like text to links. Note: Gmail often does this anyways.',
      type: 'boolean',
      default: false,
      order: 6
    }
  }
};

export default Config;
