'use babel';

var css_options = [
  'agate', 'androidstudio', 'arduino-light', 'arta', 'ascetic', 'atelier-cave-dark',
  'atelier-cave-light', 'atelier-dune-dark', 'atelier-dune-light', 'atelier-estuary-dark',
  'atelier-estuary-light', 'atelier-forest-dark', 'atelier-forest-light', 'atelier-heath-dark',
  'atelier-heath-light', 'atelier-lakeside-dark', 'atelier-lakeside-light', 'atelier-plateau-dark',
  'atelier-plateau-light', 'atelier-savanna-dark', 'atelier-savanna-light', 'atelier-seaside-dark',
  'atelier-seaside-light', 'atelier-sulphurpool-dark', 'atelier-sulphurpool-light', 'atom-one-dark',
  'atom-one-light', 'brown-paper', 'codepen-embed', 'color-brewer', 'darcula', 'dark', 'darkula',
  'default', 'docco', 'dracula', 'far', 'foundation', 'github', 'github-gist', 'googlecode',
  'grayscale', 'gruvbox-dark', 'gruvbox-light', 'hopscotch', 'hybrid', 'idea', 'ir-black',
  'kimbie.dark', 'kimbie.light', 'magula', 'monokai', 'monokai-sublime', 'mono-blue', 'obsidian',
  'ocean', 'paraiso-dark', 'paraiso-light', 'pojoaque', 'purebasic', 'qtcreator_dark',
  'qtcreator_light', 'railscasts', 'rainbow', 'routeros', 'school-book', 'solarized-dark',
  'solarized-light', 'sunburst', 'tomorrow', 'tomorrow-night', 'tomorrow-night-blue',
  'tomorrow-night-bright', 'tomorrow-night-eighties', 'vs', 'vs2015', 'xcode', 'xt256', 'zenburn'
];

const Config = {
  schema: {
    client_secret: {
      title: 'Client Secret',
      type: 'string',
      default: '',
      description: 'The contents of the `client_secret.json` file downloaded from the Google Developers Console. See the Installation section of the README for instructions.',
      order: 1
    },
    oauth_token: {
      title: 'OAuth2 Token',
      type: 'string',
      default: '',
      description: 'OAuth2 token generated by atom-gmail:authenticate. Do not touch this manually.',
      order: 2
    },
    code_highlighting: {
      title: 'Code highlighting style',
      type: 'string',
      enum: css_options,
      default: 'github',
      description: 'See [https://highlightjs.org/static/demo/](https://highlightjs.org/static/demo/) to inspect styles.',
      order: 3
    },
    font_size: {
      title: 'Font Size',
      type: 'integer',
      default: 15,
      description: 'Font size to use for regular text.',
      order: 4
    },
    max_width: {
      title: 'Maximum width',
      type: 'string',
      default: '720px',
      description: 'Maximum width of email. Can be pixels or percent. See [here](https://www.w3schools.com/cssref/pr_dim_max-width.asp) for reference.',
      order: 5
    },
    centered: {
      title: 'Centered',
      type: 'boolean',
      default: true,
      description: 'Center text in email',
      order: 6
    },
    linkify: {
      title: 'Linkify',
      description: 'Autoconvert URL-like text to links. Note: Gmail often does this anyways.',
      type: 'boolean',
      default: false,
      order: 7
    }
  }
};

export default Config;
